work_dir: sysu-adam0.9

fp16: false

# dataset
sample_method: identity_uniform
p_size: 8
k_size: 8

dataset: sysu

# architecture
last_stride: 1

# optimizer
lr: 0.01
optimizer: adam
betas: [ 0.5,0.999 ]
num_epoch: 120
lr_step: [ 40,70 ]

# augmentation
random_flip: true
random_crop: true
random_erase: true
color_jitter: false
padding: 10


# log
log_period: 50
eval_interval: 10



